#!/usr/bin/env bash
#script to display information about subdomains

domain=$1
subdomain=$2

get_dns() {
  local sub=$1
  local record_type=$2
  local dns_info=$(dig +short $sub.$domain $record_type)
  echo "The subdomain $sub is a $record_type record and points to $dns_info"
}

#default subdomains and specified subdomain
if [ -n "$subdomain" ]; then
  get_dns $subdomain A
else
  get_dns www A
  get_dns lb-01 A
  get_dns web-01 A
  get_dns w
fi
