#!/usr/bin/env bash
#Bash script that displays info on subdomains

domain_check () {
	dig "$2.$1" | awk '/ANSWER\sSECTION/{getline;split($1,s,"."); print "The subdomain " s[1] " is a " $4 " record and points to "$5;}'
    }

if [ "$#" == 1 ]
then
    for s in "www" "lb-01" "web-01" "web-02"
    do
        domain_check "$1" "$s" 
    done
elif [ "$#" == 2 ]
then
	domain_check "$1" "$2"
fi
