#!/usr/bin/env bash
# a script display information about the subdomains

domain_check() {
    string = $(dig "$2"."$1" | grep - A1 'ANSWER SECTION:' | tail - 1)
    echo "$2 $string" | awk '{print "The subdomain " $1 " is a " $5 " \
record and points to " $6}'
}

if ["$#" == 1]
then
    domain_check "$1" "www"
    domain_check "$1" "lb-01"
    domain_check "$1" "web-01"
    domain_check "$1" "web-02"
elif ["$#" == 2]
then
    domain_check "$1" "$2"
fi
