#!/usr/bin/env bash
#Creates file, displays indefinitely, SIGTERM signal, SIGINT signal and deletes
#file on SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && exit' SIGTERM
	trap 'echo "Y U no love me?!" && exit' SIGINT
	trap 'rm "/var/run/myscript.pid"' SIGQUIT || SIGTERM
done
