#!/usr/bin/env bash
#FizzBuzz with Bash. Let's have some fun Amigo

i=1
while [ $i -le 100 ]
do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		echo FizzBuzz
	elif ((i % 3 == 0))
	then
		echo Fizz
	elif ((i % 5 == 0))
	then
		echo Buzz
	else
		echo $i
	fi
	((i++))
done
