#!/usr/bin/env bash
#Displays Best School ten times but for the 9th iteration display Best school then Hi

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	((i++))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
