#!/usr/bin/env bash

sudo service nginx stop
sudo pkill apache2

# replaces the commented out line "#user www-data;" with "user nginx;"
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
#replaces the listen 80 default_server; line with listen 8080 default_server;
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
#replaces the "listen [::]:80" line with "listen [::]:8080"
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
#tests the Nginx configuration to make sure it is valid
sudo nginx -t

sudo service nginx start
